permission.use: "setplotowner.use"
permission.admin: "setplotowner.admin"
message.usage: "§8[§cPlotOwner§8] §7Bitte verwende: §c/setplotowner <Spieler>"
message.noRights: "§8[§cPlotOwner§8] §7Dazu hast du keine Rechte!"
message.noPlot: "§8[§cPlotOwner§8] §7Du bist auf keinem Plot!"
message.targetOffline: "§8[§cPlotOwner§8] §7Der Spieler §c{0} §7ist nicht online!"
message.error: "§8[§cPlotOwner§8] §7Du bist nicht berechtigt, diese Aktion durchzuführen!"
message.success.player: "§8[§cPlotOwner§8] §7Du hast das Plot an §c{0} §7gegeben!"
message.success.target: "§8[§cPlotOwner§8] §7Du hast ein Plot von §c{0} §7bekommen! §8[§c{1}§8]"